package com.abc.ceop.model.entities;

public interface Configuration {
	
	public enum FirstProcessConfiguration implements Configuration {
		INPUT_FTP_HOST, INPUT_FTP_USERNAME, INPUT_FTP_PASSWORD, INPUT_FTP_PATH,
		OUTPUT_FTP_HOST, OUTPUT_FTP_USERNAME, OUTPUT_FTP_PASSWORD, OUTPUT_FTP_PATH,
		LOCAL_PREFIX, INTERNATIONAL_PREFIX, TEMP_PATH,
		SMTP_HOST, SMTP_PORT, SMTP_AUTH, SMTP_TLS, EMAIL_USER, EMAIL_PASSWORD, 
		VALID_CAMPAIGN, DIALED_DIRECT;
	}
	
	public enum SecondProcessConfiguration implements Configuration {
		INPUT_FTP_HOST, INPUT_FTP_USERNAME, INPUT_FTP_PASSWORD, INPUT_FTP_PATH,
		OUTPUT_FTP_HOST, OUTPUT_FTP_USERNAME, OUTPUT_FTP_PASSWORD, OUTPUT_FTP_PATH,
		TEMP_PATH, NO_SUSCRIBER_TIME, PATH_MAIL_SEND, SUBJECT_MAIL, DAYS_QRLE, DAYS_EMAIL_SUS_WEB;
	}
	
}
